import fs from "fs-extra";
import type { ExchangeType } from "@/lib/exchange";
import { resolvePersistentStorageRoot } from "@/lib/persistent-storage-root";
import type { PredictionEngineMemory, VolatilityPoint } from "@/lib/dynamic";
import moment from "moment-timezone";

const IS_RAILWAY = !!process.env.RAILWAY_ENVIRONMENT;
const ACCOUNT_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
type StorageMode = "live" | "sandbox";

/**
 * Both development and production
 */
export const CACHE_DIR = resolvePersistentStorageRoot();

// PROD:STORAGE_SOURCE_OF_TRUTH
export const PROD_DIR = `${CACHE_DIR}/prod`;
export const DEV_DIR = `${CACHE_DIR}/dev`;

/** Account slugs double as directory names; reject anything that escapes. */
function accountDir(slug: string): string {
  if (!ACCOUNT_SLUG_PATTERN.test(slug)) {
    throw new Error(`Invalid exchange account slug: ${slug}`);
  }

  return `${PROD_DIR}/accounts/${slug}`;
}

function accountModeFiles(slug: string, mode: StorageMode) {
  const dir = `${accountDir(slug)}/${mode}`;

  return {
    dir,
    positions: `${dir}/positions.json`,
    balance: `${dir}/balance.json`,
    balanceSnapshots: `${dir}/balance_snapshots.json`,
  };
}

const PROD_FILES = {
  root: PROD_DIR,
  accounts: `${PROD_DIR}/accounts.json`,
  accountsRoot: `${PROD_DIR}/accounts`,
  config: `${PROD_DIR}/config.json`,
  notifications: `${PROD_DIR}/notifications.json`,
  queue: `${PROD_DIR}/queue.json`,
  status: `${PROD_DIR}/status.json`,

  accountRoot: accountDir,
  account: accountModeFiles,

  cache: {
    ip: `${PROD_DIR}/cache/ip.json`,
    marketCap: `${PROD_DIR}/cache/marketcap.json`,
    notificationDedupe: `${PROD_DIR}/cache/notification-dedupe.json`,
    ticker24h: (exchangeType: ExchangeType, marketType: string) =>
      `${PROD_DIR}/cache/ticker-24h-${exchangeType}-${marketType.toLowerCase()}.json`,
  },

  logs: {
    binanceCooldowns: `${PROD_DIR}/logs/binance_cooldowns.json`,
    errors: `${PROD_DIR}/logs/errors.json`,
    management: `${PROD_DIR}/logs/management.json`,
    safeHaven: `${PROD_DIR}/logs/safe_haven.json`,
    withdrawals: `${PROD_DIR}/logs/withdrawals.json`,
  },

  history: (mode: StorageMode) => `${PROD_DIR}/history/${mode}`,
  historyFile: (mode: StorageMode, symbol: string) =>
    `${PROD_DIR}/history/${mode}/${symbol}.json`,

  volatility: (exchangeType: ExchangeType) =>
    `${PROD_DIR}/volatility/${exchangeType}`,

  volatilityPoints: {
    get: async (
      exchangeType: ExchangeType,
      symbol: string,
    ): Promise<VolatilityPoint[]> => {
      try {
        const memory = (await fs.readJson(
          `${PROD_FILES.volatility(exchangeType)}/${symbol}.json`,
        )) as PredictionEngineMemory;

        return memory.lastVolatility;
      } catch {
        return [];
      }
    },
  },

  getCachePrefix: (prefix: string) =>
    `./storage/cache/${prefix}/${moment().format("DD_MMM_YYYY_HH")}_`,
} as const;

const DEV_FILES = {
  root: DEV_DIR,
  leaderboards: `${DEV_DIR}/leaderboards.json`,
  precisionTestCaseDir: `${DEV_DIR}/precision-test-case`,
  precisionTestCaseActive: `${DEV_DIR}/precision-test-case.json`,
} as const;

export const FILES = {
  prod: PROD_FILES,
  dev: DEV_FILES,
} as const;

export const FOLDER = {
  development: {
    btest: "src/__dev__/storage/development/backtest-volatility",
  },
  production: {
    autoGenerated: "src/__dev__/storage/production/auto-generated",
    btest: "src/__dev__/storage/production/backtest-volatility",
  },
};

/** Creates the storage directories synchronously at module load. */
function bootstrap() {
  fs.ensureDirSync(CACHE_DIR);
  fs.ensureDirSync(PROD_DIR);
  fs.ensureDirSync(DEV_DIR);
  fs.ensureDirSync(`${PROD_DIR}/cache`);

  if (!IS_RAILWAY) {
    fs.ensureDirSync("src/__dev__/storage/development/backtest-volatility");
    fs.ensureDirSync("src/__dev__/storage/production/backtest-volatility");
    fs.ensureDirSync("src/__dev__/storage/production/auto-generated");
  }
}

bootstrap();
