import fs from "fs-extra";
import type { ExchangeType } from "@/lib/exchange";
import { storageFiles } from "@/lib/system/storage";
import runtimeStorage from "@/lib/system/storage/runtime";
import moment from "moment-timezone";

const IS_RAILWAY = !!process.env.RAILWAY_ENVIRONMENT;

/**
 * Both development and production
 */
export const CACHE_DIR = storageFiles.root;

// PROD:STORAGE_SOURCE_OF_TRUTH
export const PROD_DIR = storageFiles.prod.root;
export const DEV_DIR = storageFiles.dev.root;

const PROD_FILES = {
  root: storageFiles.prod.root,
  accounts: storageFiles.prod.accounts,
  accountsRoot: storageFiles.prod.accountsRoot,
  config: storageFiles.prod.config,
  notifications: storageFiles.prod.notifications,
  queue: storageFiles.prod.queue,
  status: storageFiles.prod.status,

  accountRoot: storageFiles.prod.accountRoot,
  account: storageFiles.prod.account,

  cache: {
    ip: storageFiles.prod.cache.ip,
    marketCap: storageFiles.prod.cache.marketCap,
    notificationDedupe: storageFiles.prod.cache.notificationDedupe,
    ticker24h: storageFiles.prod.cache.ticker24h,
  },

  logs: {
    binanceCooldowns: storageFiles.prod.logs.binanceCooldowns,
    errors: storageFiles.prod.logs.errors,
    management: storageFiles.prod.logs.management,
    safeHaven: storageFiles.prod.logs.safeHaven,
    withdrawals: storageFiles.prod.logs.withdrawals,
  },

  history: storageFiles.prod.history,
  historyFile: storageFiles.prod.historyFile,

  volatility: storageFiles.prod.volatility,

  volatilityPoints: {
    get: async (
      exchangeType: ExchangeType,
      symbol: string,
    ) => runtimeStorage.vpoints.read({ exchangeType, symbol }),
  },

  getCachePrefix: (prefix: string) =>
    `./storage/cache/${prefix}/${moment().format("DD_MMM_YYYY_HH")}_`,
} as const;

const DEV_FILES = {
  root: storageFiles.dev.root,
  leaderboards: storageFiles.dev.leaderboards,
  precisionTestCaseDir: storageFiles.dev.precisionTestCaseDir,
  precisionTestCaseActive: storageFiles.dev.precisionTestCaseActive,
} as const;

export const FILES = {
  prod: PROD_FILES,
  dev: DEV_FILES,
} as const;

export const FOLDER = {
  development: {
    btest: "src/__dev__/storage/development/backtest-volatility",
  },
  production: {
    autoGenerated: "src/__dev__/storage/production/auto-generated",
    btest: "src/__dev__/storage/production/backtest-volatility",
  },
};

/** Creates the storage directories synchronously at module load. */
function bootstrap() {
  fs.ensureDirSync(CACHE_DIR);
  fs.ensureDirSync(PROD_DIR);
  fs.ensureDirSync(DEV_DIR);
  fs.ensureDirSync(`${PROD_DIR}/cache`);

  if (!IS_RAILWAY) {
    fs.ensureDirSync("src/__dev__/storage/development/backtest-volatility");
    fs.ensureDirSync("src/__dev__/storage/production/backtest-volatility");
    fs.ensureDirSync("src/__dev__/storage/production/auto-generated");
  }
}

bootstrap();
